### ISSUE TITLE
Live editor

### ISSUE THREAD

**Issue by nathobson** [craftapi/htmlcache#11]
As expected, when running the plugin the live editor seems to have no effect, presumably as it's serving a static page. Is there any workaround for this or plan to not run live edits through the cache?

**Comment by webremote** [comment]
It should be disabled for previews, it uses the request service to check if
its a livepreview or not..

Op vr 8 apr. 2016 11:55 schreef nathobson notifications@github.com:

**Comment by webremote** [comment]
FYI: it's unexpected behaviour as it's defined here:

https://github.com/craftapi/htmlcache/blob/master/services/Htmlcache_HtmlcacheService.php#L44

**Comment by nathobson** [comment]
OK, I'll run some more tests to see if it's an issue my end, which it sounds like it might be.

**Comment by nathobson** [comment]
OK, a different environment and all appears well. I believe it might might be down to cache headers that were being added automatically by another host's setup which would stop live edit working regardless of having htmlcache active. I'm a dope :)

**Comment by webremote** [comment]
No problem, appreciate the feedback nonetheless!

**Comment by nathobson** [comment]
Appreciate the crazy fast responses and thanks for releasing the plugin :+1:
