### ISSUE TITLE
Cant find plugin folder/file

### ISSUE THREAD

**Issue by espensgr** [craftapi/htmlcache#13]
When i installed the plugin with the UberCache the require_once to the htmlcache.php file written too index.php is wrong.
My plugin folder is on the same level as the craft folder so the path don't add up.
How about using the path too the pluginfolder with CRAFT_PLUGINS_PATH?
So this should always work: 

```
/*HTMLCache Begin*/require_once CRAFT_PLUGINS_PATH . 'htmlcache' . DIRECTORY_SEPARATOR . 'functions' . DIRECTORY_SEPARATOR . 'htmlcache.php';
htmlcache_checkCache();/*HTMLCache End*/
```

**Comment by webremote** [comment]
Yep, acknowledged! Will implement in next release
