### ISSUE TITLE
Any update soon?

### ISSUE THREAD

**Issue by winterstetter** [craftapi/htmlcache#18]
Hey Chris? Any plans to optimise this further?

**Comment by webremote** [comment]
hi thomas, i'm still working on it. currently testing the twig extensions and better handling for the full page caching. craft's been terribly slow on my work pc, 20-25 seconds per request, which doesn't really help me out....

**Comment by johanneslamers** [comment]
any news?

**Comment by webremote** [comment]
@thomaswinterstetter - closing this issue and moving to #25
