### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by MattWilcox** [craftapi/htmlcache#19]
Due to HTMLCache giving white pages on the first request of every page, and problems with CSRF protection, we're not finding it to be useable. Unfortunately, nor can we uninstall it. After disabling it, clicking on Uninstall gives the following error:

`Fatal error: Call to undefined function htmlcache_indexEnabled() in /Users/matt/Sites/_git/_craftvb/craft/plugins/htmlcache/HtmlcachePlugin.php on line 221`

**Comment by webremote** [comment]
that's really weird matt, which tag did you download?

**Comment by johndwells** [comment]
I'm seeing this too - didn't download a tag, just off the HEAD of master branch. Reports as v1.0.4.1 in the CP.

**Comment by johndwells** [comment]
Ah - it's because the plugin was "disabled" at the time.  Looks like HtmlcachePlugin::onBeforeUninstall() needs to make sure that `htmlcache_indexEnabled()` exists.

**Comment by luke-nehemedia** [comment]
@MattWilcox Have you found any good alternative that did work with forms?
