### ISSUE TITLE
Error when installing, trying to enter settings

### ISSUE THREAD

**Issue by aladrach** [craftapi/htmlcache#2]
I've been looking for a plugin like this for quite some time! Hope this works out!

When I try to install the plugin, I get the below error. If I leave and try to go into the plugin settings I see the same error.

Internal Server Error
Craft\Model and its behaviors do not have a method or closure named "enableGeneral".

Running Craft Pro 2.5.2767

**Comment by webremote** [comment]
Fixed in 1.0.4.1!
