### ISSUE TITLE
Exclude entries from cache

### ISSUE THREAD

**Issue by luke-nehemedia** [craftapi/htmlcache#23]
I'm very happy with this plugin but all my forms (I'm using am [amforms](https://github.com/am-impact/amforms)) aren't working anymore when I enable the UberCache-setting.

Is there a way to exclude certain pages from caching?

**Comment by luke-nehemedia** [comment]
I cannot use the plugin at all, since CSRF-form validation fails with the caching enabled

**Comment by webremote** [comment]
cc #10 #22 #27
