### ISSUE TITLE
FR: Place _cached folder in craft storage folder 

### ISSUE THREAD

**Issue by johanneslamers** [craftapi/htmlcache#3]
Feature request: place the _cached folder inside the "storage" folder of craft and rename to htmlcache. This is better for file permissions and it will make things more clear. And it makes is also easier to exclude with gitignore.

**Comment by yoannisj** [comment]
I just installed the newest version of htmlcache, and it seems that you have to manually create the "htmlcache" folder inside "craft/storage/runtime" in order for htmlcache to work and place cached files in there.

**Comment by webremote** [comment]
Hi @yoannisj, please download the latest master. This bug should be fixed now :)
