### ISSUE TITLE
Notice: Undefined index: REQUEST_SCHEME

### ISSUE THREAD

**Issue by KoenRijpstra** [craftapi/htmlcache#31]
```
Notice: Undefined index: REQUEST_SCHEME in /home/vagrant/Code/mydomain.com/craft/plugins/htmlcache/functions/htmlcache.php on line 25
```

**Comment by webremote** [comment]
Hi @KoenRijpstra, if you redownload the master (or manually update the htmlcache/functions/htmlcache.php file), a hotfix is provided

**Comment by KoenRijpstra** [comment]
Hi @webremote thanks for the quick response and hotfix! The REQUEST_SCHEME isn't reliable at all but i don't think setting the REQUEST_SCHEME if empty is the best solution. I will make a pull request with some code improvements.

**Comment by webremote** [comment]
Thanks @KoenRijpstra!
