### ISSUE TITLE
Generates empty cached sitemaps

### ISSUE THREAD

**Issue by almeric** [craftapi/htmlcache#9]
Hi,

Using your plugin in combination with this one: https://github.com/joshuabaker/craft-sitemap breaks the generated sitemap.

It generates a sitemap_xml.cached.html file which is empty. Maybe never cache xml requests?

For now I've hacked a 'solution' in `canCreateCacheFile` returning false if the requestUri contains `sitemap.xml`

**Comment by webremote** [comment]
Will investigate, the plugin should play nice with other plugins

**Comment by webremote** [comment]
hi @almeric, if you're still using the plugin, could you update to the latest master? i hope this fixes your bug as well

**Comment by almeric** [comment]
Looks like it's fixed! Thanks!
